# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Comment this line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

target 'MGDYZB' do

	pod 'Alamofire', '~> 2.0.2'
   	pod 'Kingfisher', '~> 1.9.0'
    pod 'pop', '~> 1.0.9'
#    pod 'PullToRefreshKit' // 刷新框架 https://cocoapods.org/pods/PullToRefreshKit
end
